### ISSUE TITLE
Nice work so far! a couple of things though...

### ISSUE THREAD

**Issue by barbazul** [pocallaghan/mephing#1]
I just cloned this repo and gave it a few tries until I figured it all out (not being very experienced with phing made it a little tricker) 

In the end everything went fine and I got a package but:
1. After running "phing generate" the module activation file (Foo_Bar.xml) got misplaced in app/etc/ instead of app/etc/modules/
2. When trying to add it to my pear channel using pirum I got the following error: _The PEAR package "Foo_Bar/mephing/releases/Foo_Bar_v0_0_1.tar" filename is badly formatted._ Now as I understand it, the filename should have been named "Foo_Bar-0.0.1.tgz". I'll play around with this and see if I can come out with a solution for it, but I thought it would be best to let you know first.

**Comment by pocallaghan** [comment]
Hi barbazul,

Thanks for the interest, I'm glad you worked it out. This was actually my first foray into phing, which was one of the reasons behind the package, to teach myself to use it. To be honest this was a project that I started awhile ago with lots of ideas, but as I've been so busy with work and other commitments, I've not really managed to spend much time on it since my original commits. I'll happily merge in any changes you make that I feel stick to the overal ethos of the project (i.e. making it easier to develop Magento Extensions).

Hopefully when my work commitments steer me back into Magento development I'll find the drive / spare time to tidy it up and start adding new features.
